CRS/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'CRS'

urlpatterns = [
    path('', views.index, name='index'),
    path('professor/list/<int:professor_id>/',
         views.professor_detail, name='professor_detail'),
    path('professor/create/', views.professor_create, name='professor_create'),
    path('professor/list/', views.professor_list, name='professor_list'),
    path('student/list/', views.student_list, name='student_list'),
    path('student/list/<int:student_id>/',
         views.student_detail, name='student_detail'),
    path('student/create/', views.student_create, name='student_create'),
    path('subject/list/', views.subject_list, name='subject_list'),
    path('subject/create/', views.subject_create, name='subject_create'),
    path('signup/list', views.signup_list, name='signup_list'),

    path('login/', auth_views.LoginView.as_view(template_name='CRS/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='CRS/logout.html'), name='logout'),

    path('attendance_create/', views.attendance_create, name='attendance_create'),
    path('attendance_remove/', views.attendance_remove, name='attendance_remove'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from CRS import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('CRS/', include('CRS.urls')),
    path('', views.index, name='index'),  # '/' 에 해당되는 path
]

CRS/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import User


#  교수
class Professor(models.Model):
    professor_no = models.IntegerField(validators=[MinValueValidator(
        10000), MaxValueValidator(99999)], help_text="교번 5자리를 입력하세요", primary_key=True)
    name = models.CharField(max_length=30)
    email = models.EmailField()
    telno = models.CharField(max_length=30)
    create_date = models.DateTimeField()

    def __str__(self):
        return self.name


class Users(AbstractUser):
    user_no = models.IntegerField(null=True)
    user_type = models.CharField(max_length=1, default='0')  # 1: 교수, 2: 학생


# 과목(교수)
class Subject(models.Model):
    subject_code = models.AutoField(primary_key=True) # 과목코드
    professor_no = models.ForeignKey(Professor, on_delete=models.CASCADE) # 교수번호
    subject_name = models.CharField(max_length=80) # 과목명
    maximum_num = models.IntegerField(default=30)  # 제한인원
    current_num = models.IntegerField(default=0)   # 현재인원
    lecture_day = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(6)]) # 강의일
    lecture_time = models.IntegerField(default=100000000)      # 수강시간
    lecture_room = models.CharField(default="A001", max_length=30) # 강의실
    create_date = models.DateTimeField()

    def __str__(self):
        return self.subject_name


# 학생
class Student(models.Model):
    student_no = models.IntegerField(validators=[MinValueValidator(
        10000000), MaxValueValidator(99999999)], help_text="학번 8자리를 입력하세요", primary_key=True)
    name = models.CharField(max_length=30)
    email = models.EmailField()
    telno = models.CharField(max_length=30)
    create_date = models.DateTimeField()

    def __str__(self):
        return self.name


# 출석부(과목)
class Attendance(models.Model):
    attendance_code = models.AutoField(primary_key=True)
    subject_code = models.ForeignKey(Subject, on_delete=models.CASCADE, null=False)
    student_no = models.ForeignKey(Student, on_delete=models.CASCADE, null=False)

CRS/forms.py
from django import forms
from django.core.validators import MaxValueValidator
from CRS.models import Professor
from CRS.models import Student
from CRS.models import Subject
from CRS.models import Users


class SubjectForm(forms.ModelForm):
    class Meta:
        model = Subject  # 사용할 모델
        fields = ['subject_code', 'professor_no',
                  'subject_name', 'lecture_day', 'lecture_time', 'lecture_room']  # ProfessorForm에서 사용할 모델의 속성
        widgets = {
            # 'subject': forms.TextInput(attrs={'class': 'form-control'}),
            # 'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 10}),
        }
        labels = {
            'subject_code': '과목코드',
            'professor_no': '교번',
            'subject_name': '과목이름',
        }


class StudentForm(forms.ModelForm):
    class Meta:
        model = Student  # 사용할 모델
        fields = ['student_no', 'name', 'email',
                  'telno']  # StudentForm 사용할 모델의 속성
        widgets = {
            # 'subject': forms.TextInput(attrs={'class': 'form-control'}),
            # 'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 10}),
        }
        labels = {
            'student_no': '학번',
            'name': '이름',
            'email': '이메일',
            'telno': '전화번호',
        }


class ProfessorForm(forms.ModelForm):
    class Meta:
        model = Professor  # 사용할 모델
        fields = ['professor_no', 'name', 'email',
                  'telno']  # ProfessorForm에서 사용할 모델의 속성
        widgets = {
            # 'subject': forms.TextInput(attrs={'class': 'form-control'}),
            # 'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 10}),
        }
        labels = {
            'professor_no': '교번',
            'name': '이름',
            'email': '이메일',
            'telno': '전화번호',
        }


class RegisterForm_pro(forms.Form):
    professor_no = forms.IntegerField(validators=[MaxValueValidator(
        10000), MaxValueValidator(99999)], label="교번 5자리를 입력하세요")
    name = forms.CharField(max_length=30)
    email = forms.EmailField()
    telno = forms.CharField(max_length=30)
    password = forms.CharField(widget=forms.PasswordInput)


class RegisterForm_stu(forms.Form):
    student_no = forms.IntegerField(validators=[MaxValueValidator(
        10000000), MaxValueValidator(99999999)], label="학번 8자리를 입력하세요")
    name = forms.CharField(max_length=30)
    email = forms.EmailField()
    telno = forms.CharField(max_length=30)
    password = forms.CharField(widget=forms.PasswordInput)

CRS/views.py
from django.http import HttpResponse
from django.http.response import JsonResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from .models import Professor
from .forms import ProfessorForm, RegisterForm_pro, RegisterForm_stu
from .models import Student
from .forms import Users
from .models import Users

from .forms import StudentForm
from .models import Subject
from .forms import SubjectForm
from django.db import transaction

from .models import Attendance
from django.views.decorators.csrf import csrf_exempt


def index(request):
    return render(request, 'index.html')


def professor_list(request):
    """ 
    교수 리스트 출력
    """
    professor_list = Professor.objects.order_by('-create_date')
    context = {'professor_list': professor_list}
    return render(request, 'CRS/professor_list.html', context)


def professor_detail(request, professor_id):
    """
    교수 내용 출력
    """
    print("교수 상세내역")
    professor = Professor.objects.get(professor_no=professor_id)
    context = {'professor': professor}
    return render(request, 'CRS/professor_detail.html', context)


def professor_create(request):
    """ 교수 등록 """
    template_name = 'CRS/professor_form.html'

    if request.method == 'POST':
        with transaction.atomic():
            professor = Professor(
                professor_no=request.POST['professor_no'],
                name=request.POST['name'],
                email=request.POST['email'],
                telno=request.POST['telno'],
                create_date=timezone.now(),
            )
            professor.save()
            user = Users(
                username=request.POST['professor_no'],
                email=request.POST['email'],
                is_staff=False,
                is_superuser=False,
                is_active=True,
                user_no=request.POST['professor_no'],
                user_type='1',
            )
            user.set_password(request.POST['password'])
            user.save()
            professor_list = Professor.objects.order_by('-create_date')
            context = {'professor_list': professor_list}
            return render(request, 'CRS/professor_list.html', context)
    else:
        form = RegisterForm_pro()
    context = {'form': form}
    return render(request, template_name, context)


def student_list(request):
    """    학생 리스트 출력    """
    print("학생 리스트 출력 !!!")
    student_list = Student.objects.order_by('-create_date')
    context = {'student_list': student_list}
    return render(request, 'CRS/student_list.html', context)


def student_detail(request, student_id):
    """
    학생 내용 출력
    """
    student = Student.objects.get(student_no=student_id)
    context = {'student': student}
    return render(request, 'CRS/student_detail.html', context)


def student_create(request):
    """ 학생 등록 """
    template_name = 'CRS/student_form.html'

    if request.method == 'POST':
        with transaction.atomic():
            student = Student(
                student_no=request.POST['student_no'],
                name=request.POST['name'],
                email=request.POST['email'],
                telno=request.POST['telno'],
                create_date=timezone.now(),
            )
            student.save()
            user = Users(
                username=request.POST['student_no'],
                email=request.POST['email'],
                is_staff=False,
                is_superuser=False,
                is_active=True,
                user_no=request.POST['student_no'],
                user_type='2',
            )
            user.set_password(request.POST['password'])
            user.save()
            student_list = Student.objects.order_by('-create_date')
            context = {'student_list': student_list}
            return render(request, 'CRS/student_list.html', context)
    else:
        form = RegisterForm_stu()
    context = {'form': form}
    return render(request, template_name, context)


def subject_list(request):
    """
    과목 리스트 출력
    """
    subject_list2 = Subject.objects.filter(professor_no=request.user.user_no)
    context = {'subject_list': subject_list2}
    return render(request, 'CRS/subject_list.html', context)


def subject_create(request):
    """
    과목 등록
    """

    if request.method == 'POST':
        val0 = request.POST['lecture_time']
        val1 = val0.split(',')  # 리스트로 받아온 값을 콤마로 나누어서 리스트로 만들어준다.
        val2 = [int(i) for i in val1]  # 리스트 내부의 값을 숫자로 형변환
        val3 = sum(val2)  # 형변환된 리스트 내의 숫자를 모두 더해서 합을 구한다.
        val4 = str(val3)  # 인덱스를 사용하기 위해 문자열로 형변환
        val5 = val4[1:]  # 첫번째 문자열 삭제

        subject = Subject(
            professor_no_id=request.user.user_no,
            subject_name=request.POST['subject_name'],
            maximum_num=request.POST['maximum_num'],
            lecture_day=request.POST['lecture_day'],
            lecture_time=val5,
            lecture_room=request.POST['lecture_room'],
            create_date=timezone.now(),
        )
        subject.save()
        return redirect('CRS:index')
    else:
        form = SubjectForm()
    context = {'form': form}
    return render(request, 'CRS/subject_form.html', context)


def signup_list(request):
    """
    수강신청과목 리스트 출력
    """
    mysubject_count = Attendance.objects.select_related(
        'subject_code').filter(student_no_id=request.user.user_no)
    my_arr = []

    for list in mysubject_count:
        my_arr.append(list.subject_code.subject_code)

    subject_list = Subject.objects.exclude(
        subject_code__in=my_arr)  # 내가 신청한 수강신청내역 제외
    subject_count = Subject.objects.count()

    context = {'subject_list': subject_list,
               'subject_count': subject_count, 'mysubject_count': mysubject_count}
    return render(request, 'CRS/signup_list.html', context)


@csrf_exempt
def attendance_remove(request):
    """
    수업철회
    """
    if request.method == 'POST':
        user_id = request.user.user_no   # 세션에서 로그인한 유저의 번호 가져오기
        subject = Subject.objects.get(
            subject_code=request.POST['subject_code'])
        attendance = Attendance.objects.get(
            subject_code_id=subject, student_no_id=user_id)
        current_num = subject.current_num - 1
        subject.current_num = subject.current_num - 1

        if (current_num > subject.maximum_num):
            return JsonResponse({'result': 'fail'})
        else:
            with transaction.atomic():
                subject.save()
                attendance.delete()
            return JsonResponse({'result': 'success'})
    else:
        return render(request, 'CRS/singup_list.html')


@csrf_exempt
def attendance_create(request):
    """
    수업신청
    """
    if request.method == 'POST':
        user_id = request.user.user_no   # 세션에서 로그인한 유저의 번호 가져오기
        # 과목의 신청자수를 증가시키기 위해 과목 정보 가져오기
        subject = Subject.objects.get(
            subject_code=request.POST['subject_code'])
        current_num = subject.current_num + 1
        subject.current_num = subject.current_num + 1

        if (current_num > subject.maximum_num):      # 해당 과목의 인원이 초과되었으면 신청실패
            return JsonResponse({'result': 'fail'})
        else:
            attendance = Attendance(
                subject_code_id=request.POST['subject_code'],
                student_no_id=user_id,
            )
            with transaction.atomic():
                subject.save()
                attendance.save()
            return JsonResponse({'result': 'success'})
    else:
        return render(request, 'CRS/singup_list.html')

templates/CRS/login.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <form method="post" class="post-form" action="{% url 'CRS:login' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username" value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="form-group">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password" value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
</div>
{% endblock %}

templates/CRS/professor_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>{{ professor.name }}</h1>

<div>
    {{ professor.professor_no }}
</div>

{% endblock %}

templates/CRS/professor_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">등록</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/CRS/professor_list.html
{% extends 'base.html' %}
{% block content %}

<div class="container crs-div-1">
<table class="table table-striped table-bordered table-hover table-sm mt-3">
    <caption></caption>
        <thead>
            <tr>
                <th>교수명</th>
                <th>교번</th>
                <th>이메일</th>
                <th>전화번호</th>
                <th>생성일</th>
            </tr>
        </thead>
        <tbody>
        {% if professor_list %}

        {% for professor in professor_list %}
            <tr>
                <td><a href="{% url 'CRS:professor_detail' professor.professor_no %}">{{ professor.name }}</a></td>
                <td>{{ professor.professor_no }}</td>
                <td>{{ professor.email }}</td>
                <td>{{ professor.telno }}</td>
                <td>{{ professor.create_date }}</td>
            </tr>
        {% endfor %}
        {% else %}
            <p>데이터 없음</p>
        {% endif %}


        </tbody>
    </table>
 <a href="{% url 'CRS:professor_create' %}" class="btn btn-primary">등록</a>
</div>


{% endblock %}

templates/CRS/signup_list.html
{% extends 'base.html' %}
{% block content %}

<div class="container crs-div-1">
    <br><br>
    <h3>신청과목</h3>
<table class="table table-striped table-bordered table-hover">
        <thead>
            <tr>
                <th>과목코드</th>
                <th>과목이름</a></th>
                <th>교수명</th>
                <th>신청현황</th>
                <th>신청</th>
            </tr>
        </thead>
        <tbody>
        {% if subject_list %}

        {% for subject in subject_list %}
            <tr>
                <td>{{ subject.subject_code }}</td>
                <td>{{ subject.subject_name }}</td>
                <td>{{ subject.professor_no.name }}</td>
                {% if subject.current_num == subject.maximum_num %}
                <td class="text-danger">{{ subject.current_num }} / {{ subject.maximum_num }}</td>
                {% else %}
                <td> <span class="text-primary"> {{subject.current_num }}</span> / {{ subject.maximum_num }}</td>
                {% endif %}

                <td><form action="" method="post">{% csrf_token %}<button onclick="attendance_create('{{ subject.subject_code }}')" >신청</button></form></td>
            </tr>
        {% endfor %}
        {% else %}
            <p>데이터 없음</p>
        {% endif %}
        </tbody>
    </table>
 
<br><br>
<h3>나의 신청내역</h3>

    <table class="table table-striped table-bordered table-hover">
        {% if mysubject_count %}
        <thead>
            <tr>
                <th>과목코드</th>
                <th>과목이름</th>
                <th>교수명</th>
                <th>신청현황</th>
                <th>신청취소</th>
            </tr>
        </thead>
        <tbody>

        {% for mysubject in mysubject_count %}
            <tr>
                <td>{{ mysubject.subject_code.subject_code }}</td>
                <td>{{ mysubject.subject_code.subject_name }}</td>
                <td>{{ mysubject.subject_code.professor_no }}</td>
                {% if mysubject.subject_code.current_num == mysubject.subject_code.maximum_num %}
                <td class="text-danger">{{ mysubject.subject_code.current_num }} / {{ mysubject.subject_code.maximum_num }}</td>
                {% else %}
                <td> <span class="text-primary"> {{mysubject.subject_code.current_num }}</span> / {{ mysubject.subject_code.maximum_num }}</td>
                {% endif %}
                <td><form action="" method="post">{% csrf_token %}<button onclick="attendance_remove('{{ mysubject.subject_code.subject_code }}')" >신청취소</button></form></td>

            </tr>
        {% endfor %}
        {% else %}
            <p>데이터 없음</p>
        {% endif %}
        </tbody>
    </table>
</div>

<script>
function attendance_create(subject_code){
    if(confirm('해당과목을 신청하시겠습니까?')){
        $.ajax({
        url: "{% url 'CRS:attendance_create' %}",
        type: "POST",
        data: {
            subject_code: subject_code
        },
        success: function(data){
            alert("신청되었습니다.");
            location.reload();
        },
        error: function(data){
            alert("신청에 실패했습니다.");
        }
    });
    }else{
        return;
    }
}

function attendance_remove(subject_code){
    if(confirm('신청과목을 취소 하시겠습니까?')){
        $.ajax({
        url: "{% url 'CRS:attendance_remove' %}",
        type: "POST",
        data: {
            subject_code: subject_code
        },
        success: function(data){
            alert("신청이 취소 되었습니다.");
            location.reload();
        },
        error: function(data){
            alert("신청취소에 실패했습니다.");
        }
    });
    } else {
        return;
    }
}
</script>

{% endblock %}

templates/CRS/student_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>{{ student.name }}</h1>

<div>
    {{ student.student_no }}
</div>

{% endblock %}

templates/CRS/student_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">등록</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/CRS/student_list.html
{% extends 'base.html' %}
{% block content %}

<div class="container crs-div-1">
<table class="table table-striped table-bordered table-hover table-sm mt-3">
        <caption></caption>
        <thead>
            <tr>
                <th>학생명</th>
                <th>학번</th>
                <th>이메일</th>
                <th>전화번호</th>
                <th>생성일</th>
            </tr>
        </thead>
        <tbody>
        {% if student_list %}
        {% for student in student_list %}
            <tr>
                <td><a href="{% url 'CRS:student_detail' student.student_no %}">{{ student.name }}</a></td>
                <td>{{ student.student_no }}</td>
                <td>{{ student.email }}</td>
                <td>{{ student.telno }}</td>
                <td>{{ student.create_date }}</td>
            </tr>
        {% endfor %}
        {% else %}
            <p>데이터 없음</p>
        {% endif %}
        </tbody>
    </table>
 <a href="{% url 'CRS:student_create' %}" class="btn btn-primary">등록</a>
</div>


{% endblock %}

templates/CRS/subject_form.html
{% extends 'base.html' %}
{% block content %}

<script>
	function Chk() {
		var result = Array();
		var cnt = 0;
		var chkbox = $(".chkselect");

		for(i=0;i<chkbox.length;i++) {
			if(chkbox[i].checked == true) {
				result[cnt] = chkbox[i].value;
				cnt++;
			}
		}
		$('#id_lecture_time').val(result);
	}
</script>

<div class="container">
    <h5 class="my-3 border-bottom pb-2">등록</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        <p>
        <label for="id_subject_name">과목이름:</label> <input type="text" name="subject_name" required="" id="id_subject_name" placeholder="ex) 컴퓨터언어및실습">
    </p>
    <p><label for="id_maximum_num">최대인원 :</label><input type="number" name="maximum_num" min="10" max="80" required="" id="id_maximum_num" value=30></p>

    <p><label for="id_lecture_day">강의요일 :</label>
        <input type="radio" name="lecture_day" value="0" id="id_lecture_day" checked>월
        <input type="radio" name="lecture_day" value="1" id="id_lecture_day">화
        <input type="radio" name="lecture_day" value="2" id="id_lecture_day">수
        <input type="radio" name="lecture_day" value="3" id="id_lecture_day">목
        <input type="radio" name="lecture_day" value="4" id="id_lecture_day">금
    </p>

    <p><label for="id_lecture_time">강의시간 :</label> 
        <input type="checkbox" name="chk[]" class='chkselect' onclick='Chk();' value="1100000000">1교시
        <input type="checkbox" name="chk[]" class='chkselect' onclick='Chk();' value="1010000000">2교시
        <input type="checkbox" name="chk[]" class='chkselect' onclick='Chk();' value="1001000000">3교시
        <input type="checkbox" name="chk[]" class='chkselect' onclick='Chk();' value="1000100000">4교시
        <input type="checkbox" name="chk[]" class='chkselect' onclick='Chk();' value="1000010000">5교시
        <input type="checkbox" name="chk[]" class='chkselect' onclick='Chk();' value="1000001000">6교시
        <input type="checkbox" name="chk[]" class='chkselect' onclick='Chk();' value="1000000100">7교시
        <input type="checkbox" name="chk[]" class='chkselect' onclick='Chk();' value="1000000010">8교시
        <input type="checkbox" name="chk[]" class='chkselect' onclick='Chk();' value="1000000001">9교시
    </p>
    <input type='hidden' id='id_lecture_time' name='lecture_time'>
      
     <p><label for="lecture_room">강의실 :</label>
        
        <select name="lecture_room" id="id_lecture_room">
            <option value="본관101">본관101</option>
            <option value="본관102">본관102</option>
            <option value="복지관101">복지관101</option>
            <option value="복지관102">복지관102</option>
        </select>
    </p>

        
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/CRS/subject_list.html
{% extends 'base.html' %}
{% block content %}

<!-- <div class="container my-3 crs-div-1"> -->
    <div class="container crs-div-1">
<table class="table table-striped table-bordered table-hover table-sm mt-3">
        <caption></caption>
        <thead>
            <tr>
                <th>과목이름</th>
                <th>생성일</th>
            </tr>
        </thead>
        <tbody>
        {% if subject_list %}

        {% for subject in subject_list %}
            <tr>
                <td>{{ subject.subject_name }}</td>
                <td>{{ subject.create_date }}</td>
            </tr>
        {% endfor %}
        {% else %}
            <p>데이터 없음</p>
        {% endif %}

        </tbody>
    </table>
 <a href="{% url 'CRS:subject_create' %}" class="btn btn-primary">추가</a>
</div>


{% endblock %}