CRS/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'CRS'

urlpatterns = [
    path('', views.index, name='index'),
    path('professor/list/<int:professor_id>/',
         views.professor_detail, name='professor_detail'),
    path('professor/create/', views.professor_create, name='professor_create'),
    path('professor/list/', views.professor_list, name='professor_list'),
    path('student/list/', views.student_list, name='student_list'),
    path('student/list/<int:student_id>/',
         views.student_detail, name='student_detail'),
    path('student/create/', views.student_create, name='student_create'),
    path('subject/list/', views.subject_list, name='subject_list'),
    path('subject/create/', views.subject_create, name='subject_create'),
    path('signup/list', views.signup_list, name='signup_list'),

    path('login/', auth_views.LoginView.as_view(template_name='CRS/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='CRS/logout.html'), name='logout'),

    path('attendance_create/', views.attendance_create, name='attendance_create'),
    path('attendance_remove/', views.attendance_remove, name='attendance_remove'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from CRS import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('CRS/', include('CRS.urls')),
    path('', views.index, name='index'),  # '/' 에 해당되는 path
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Hello, world!</title>

    <script  src="http://code.jquery.com/jquery-latest.min.js"></script>


    <link rel="stylesheet" type="text/css" href="{% static 'navi.css' %}">
</head>
<body>
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
</body>
</html>

templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/index.html
{% extends 'base.html' %}
{% block content %}

<h3>안녕하세요 course register system 에 오신것을 환영합니다.</h3>

{% endblock %}

templates/navbar.html
<ul>
      {% if user.is_authenticated %} 
       {% if user.user_type == '1' %}
       <li><a href="{% url 'CRS:subject_list' %}">과목</a></li>
       <li><a class="justify-content-end navbar-right">{{ user.username }} (교수)</a></li>
       <li><a class="justify-content-end navbar-right"  href="{% url 'CRS:logout' %}">로그아웃</a></li> 
       {% elif user.user_type == '2' %}
       <li><a href="{% url 'CRS:signup_list' %}">수강신청</a></li>
       <li><a class="justify-content-end navbar-right">{{ user.username }} (학생)</a></li>
      <li><a class="justify-content-end navbar-right"  href="{% url 'CRS:logout' %}">로그아웃</a></li> 
       {% else %} 
       <li><a href="{% url 'CRS:professor_list' %}">교수</a></li>
      <li><a href="{% url 'CRS:student_list' %}">학생</a></li>
        <li><a class="justify-content-end navbar-right"> {{ user.username }} (관리자)</a></li>
        <li><a class="justify-content-end navbar-right"  href="{% url 'CRS:logout' %}">로그아웃</a></li> 
       {% endif %}
      {% else %}
      <li><a class="justify-content-end navbar-right"  href="{% url 'CRS:login' %}">로그인</a></li> 
      {% endif %}
</ul>